// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwwblpbyydswqkhqndfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3d2JscGJ5eWRzd3FraHFuZGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Nzc1NDksImV4cCI6MjA2MTQ1MzU0OX0.ELGAI3HkXox96TBj0ab95iXYUo3gw1qwOYxfmX7tiZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);